import jsPDF from "jspdf";

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - 2 * MARGIN;

function exportFullAnalysisPDF(
  input: string,
  analysis: Record<string, unknown>,
  reflectionEval?: Record<string, unknown> | null,
  reflectionAnswers?: string[] | null,
) {
  const doc = new jsPDF("p", "mm", "a4");
  let y = MARGIN;

  const addPageIfNeeded = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const addSubtitle = (text: string) => {
    addPageIfNeeded(8);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.text(text, MARGIN, y);
    y += 8;
  };

  const addLine = () => {
    addPageIfNeeded(4);
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 5;
  };

  const addBody = (text: string, indent = 0) => {
    const lines = doc.splitTextToSize(text, CONTENT_W - indent);
    addPageIfNeeded(lines.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(lines, MARGIN + indent, y);
    y += lines.length * 5 + 2;
  };

  const addBullet = (text: string) => {
    const bulletText = "\u2022  " + text;
    const lines = doc.splitTextToSize(bulletText, CONTENT_W - 4);
    addPageIfNeeded(lines.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 2;
  };

  const addLabel = (label: string) => {
    addPageIfNeeded(6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    doc.text(label, MARGIN, y);
    y += 5;
  };

  // Cover
  doc.setFillColor(15, 15, 30);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(255, 255, 255);
  doc.text("Decision Analysis Report", MARGIN, 90);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 220);
  doc.text("Generated by Reverie \u2014 AI Decision Intelligence", MARGIN, 105);
  doc.setFontSize(10);
  doc.setTextColor(140, 140, 180);
  doc.text(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, MARGIN, 115);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 160);
  doc.text("This report is a reasoning tool, not a decision maker.", MARGIN, 130);

  // Problem Statement
  doc.addPage();
  y = MARGIN;
  addSubtitle("Problem Statement");
  addLine();
  addBody(input);

  // Extraction
  const ext = analysis.extraction as Record<string, string[]> | undefined;
  if (ext) {
    addSubtitle("Semantic Extraction");
    addLine();
    for (const key of ["goals", "constraints", "priorities", "fears"] as const) {
      addLabel(key.charAt(0).toUpperCase() + key.slice(1));
      for (const item of ext[key] || []) {
        addBullet(item);
      }
      y += 2;
    }
  }

  // Belief Graph
  const graph = analysis.belief_graph as Record<string, unknown[]> | undefined;
  if (graph) {
    addSubtitle("Belief Graph");
    addLine();
    const nodes = graph.nodes as Array<Record<string, string>> | undefined;
    if (nodes) {
      for (const n of nodes) {
        addBullet(`${n.label} (${n.type})`);
      }
    }
    y += 2;
  }

  // Assumptions
  const assumptions = analysis.assumptions as Array<Record<string, string>> | undefined;
  if (assumptions) {
    addSubtitle("Assumption Stress Test");
    addLine();
    for (const a of assumptions) {
      addLabel(a.assumption);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`Evidence: ${a.evidence_strength}  |  Risk: ${a.risk_level}`, MARGIN, y);
      y += 4;
      addBody(a.explanation, 4);
      y += 2;
    }
  }

  // Contradictions
  const contradictions = analysis.contradictions as Array<Record<string, string>> | undefined;
  if (contradictions) {
    addSubtitle("Contradiction Detection");
    addLine();
    for (const c of contradictions) {
      addLabel(c.conflict);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`Severity: ${c.severity}`, MARGIN, y);
      y += 4;
      addBody(c.explanation, 4);
      y += 2;
    }
  }

  // Scenarios
  const scenarios = analysis.scenarios as Array<Record<string, string>> | undefined;
  if (scenarios) {
    addSubtitle("Counterfactual Scenarios");
    addLine();
    for (const s of scenarios) {
      addPageIfNeeded(6);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(99, 102, 241);
      doc.text(s.future, MARGIN, y);
      y += 6;
      addBody(s.description);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      addPageIfNeeded(4);
      doc.text(`Upside: ${s.upside}`, MARGIN + 4, y);
      y += 4;
      doc.text(`Downside: ${s.downside}`, MARGIN + 4, y);
      y += 4;
      doc.text(`Confidence: ${s.confidence}`, MARGIN + 4, y);
      y += 6;
    }
  }

  // Tradeoffs
  const tradeoffs = analysis.tradeoffs as Record<string, unknown> | undefined;
  if (tradeoffs) {
    addSubtitle("Tradeoff Analysis");
    addLine();
    const dims = tradeoffs.dimensions as string[] | undefined;
    if (dims) {
      addBody("Dimensions: " + dims.join(", "));
      y += 2;
    }
    const futures = tradeoffs.futures as Array<Record<string, unknown>> | undefined;
    if (futures) {
      for (const f of futures) {
        addLabel(f.future as string);
        const scores = f.scores as Array<Record<string, unknown>> | undefined;
        if (scores) {
          for (const sc of scores) {
            addBullet(`${sc.dimension}: ${sc.value}/10`);
          }
        }
        y += 2;
      }
    }
  }

  // Reflection Questions & Answers
  const questions = analysis.reflection_questions as Array<Record<string, string>> | undefined;
  if (questions) {
    addSubtitle("Decision Reflection");
    addLine();
    questions.forEach((q, i) => {
      addPageIfNeeded(6);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(99, 102, 241);
      doc.text(`Q${i + 1}: ${q.question}`, MARGIN, y);
      y += 5;
      const answer = reflectionAnswers?.[i] || "(no answer provided)";
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const ansLines = doc.splitTextToSize(answer, CONTENT_W - 4);
      addPageIfNeeded(ansLines.length * 5);
      doc.text(ansLines, MARGIN + 4, y);
      y += ansLines.length * 5 + 4;
    });

    // Reflection Evaluation
    if (reflectionEval) {
      addSubtitle("Reflection Evaluation");
      addLine();
      const re = reflectionEval as Record<string, unknown>;
      addPageIfNeeded(6);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text(`Clarity Score: ${re.clarity_score}/10`, MARGIN, y);
      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(30, 30, 30);
      doc.text("Key Insights:", MARGIN, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      for (const insight of (re.key_insights as string[]) || []) {
        addBullet(insight);
      }
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(180, 60, 60);
      addPageIfNeeded(6);
      doc.text("Blind Spots:", MARGIN, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      for (const spot of (re.blind_spots as string[]) || []) {
        addBullet(spot);
      }
      y += 3;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      const readyText = re.is_ready ? "Ready to decide." : "Needs more reflection.";
      doc.setTextColor(re.is_ready ? 34 : 180, re.is_ready ? 120 : 60, re.is_ready ? 34 : 60);
      addPageIfNeeded(6);
      doc.text(readyText, MARGIN, y);
      y += 6;
      addBody(re.summary as string);
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(`Reverie \u2014 Decision Analysis Report \u2014 Page ${i} of ${pageCount}`, MARGIN, PAGE_H - 10);
  }

  doc.save("reverie-decision-analysis.pdf");
}

function exportActionPlanPDF(plan: Record<string, unknown>, decision: string) {
  const doc = new jsPDF("p", "mm", "a4");
  let y = MARGIN;

  const addPageIfNeeded = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const addSubtitle = (text: string) => {
    addPageIfNeeded(8);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.text(text, MARGIN, y);
    y += 8;
  };

  const addLine = () => {
    addPageIfNeeded(4);
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 5;
  };

  const addBody = (text: string, indent = 0) => {
    const lines = doc.splitTextToSize(text, CONTENT_W - indent);
    addPageIfNeeded(lines.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(lines, MARGIN + indent, y);
    y += lines.length * 5 + 2;
  };

  const addBullet = (text: string) => {
    const bulletText = "\u2022  " + text;
    const lines = doc.splitTextToSize(bulletText, CONTENT_W - 4);
    addPageIfNeeded(lines.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 2;
  };

  // Cover
  doc.setFillColor(15, 15, 30);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(255, 255, 255);
  doc.text("90-Day Action Plan", MARGIN, 90);
  doc.setFontSize(12);
  doc.setTextColor(180, 180, 220);
  doc.text("Generated by Reverie \u2014 AI Decision Intelligence", MARGIN, 105);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 160);
  const decisionLines = doc.splitTextToSize(decision, CONTENT_W);
  doc.text(decisionLines, MARGIN, 120);

  // First Action
  const planRecord = plan as Record<string, unknown>;
  doc.addPage();
  y = MARGIN;
  addSubtitle("First Action \u2014 Do This Today");
  addLine();
  addBody(planRecord.first_action as string);
  y += 4;

  // Timeline phases
  const phases = [
    { label: "Days 1\u201330", key: "plan_30_day" as const },
    { label: "Days 31\u201360", key: "plan_60_day" as const },
    { label: "Days 61\u201390", key: "plan_90_day" as const },
  ];
  for (const phase of phases) {
    addSubtitle(phase.label);
    addLine();
    const steps = planRecord[phase.key] as Array<Record<string, string>> | undefined;
    if (steps) {
      for (const step of steps) {
        addPageIfNeeded(6);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(30, 30, 30);
        doc.text(step.title, MARGIN, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        addBody(step.description, 4);
        y += 2;
      }
    }
  }

  // Risk Mitigation
  addSubtitle("Risk Mitigation");
  addLine();
  for (const r of (planRecord.risk_mitigation as string[]) || []) {
    addBullet(r);
  }
  y += 2;

  // Assumptions to Validate
  addSubtitle("Assumptions to Validate");
  addLine();
  for (const a of (planRecord.assumptions_to_validate as string[]) || []) {
    addBullet(a);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(`Reverie \u2014 90-Day Action Plan \u2014 Page ${i} of ${pageCount}`, MARGIN, PAGE_H - 10);
  }

  doc.save("reverie-action-plan.pdf");
}

export { exportFullAnalysisPDF, exportActionPlanPDF };
